export const SUSPENSE_TERMS: Record<string, number> = {
  "suddenly": 2.4,
  "whisper": 1.6,
  "whispers": 1.6,
  "whispering": 1.6,
  "shadow": 1.4,
  "shadows": 1.4,
  "dark": 1.3,
  "darkness": 1.5,
  "silence": 1.5,
  "silent": 1.4,
  "scream": 2.4,
  "screams": 2.4,
  "screaming": 2.4,
  "blood": 2.0,
  "bleeding": 2.0,
  "chase": 2.2,
  "chasing": 2.2,
  "runs": 1.5,
  "running": 1.5,
  "escape": 1.8,
  "trap": 2.0,
  "trapped": 2.1,
  "locked": 1.6,
  "door": 0.9,
  "stairs": 1.1,
  "cellar": 1.5,
  "basement": 1.5,
  "attic": 1.5,
  "footsteps": 1.9,
  "breath": 1.2,
  "breathing": 1.3,
  "heart": 1.0,
  "pounding": 1.8,
  "cold": 1.0,
  "shiver": 1.6,
  "tremble": 1.6,
  "shakes": 1.3,
  "shake": 1.3,
  "knife": 2.0,
  "gun": 1.8,
  "dead": 1.7,
  "die": 1.6,
  "death": 1.7,
  "kill": 2.0,
  "killed": 2.0,
  "kills": 2.0,
  "monster": 2.0,
  "ghost": 1.8,
  "figure": 1.2,
  "voice": 1.1,
  "voices": 1.3,
  "nightmare": 2.0,
  "dream": 1.0,
  "wakes": 1.4,
  "wake": 1.2,
  "music box": 1.4,
  "scratch": 1.8,
  "scratches": 1.9,
  "creak": 1.7,
  "creaks": 1.7,
  "groan": 1.5,
  "slowly": 1.3,
  "stares": 1.3,
  "stare": 1.3,
  "watches": 1.4,
  "waiting": 1.3,
  "flicker": 1.6,
  "flickers": 1.6,
  "dies": 1.5,
  "thunder": 1.5,
  "storm": 1.3,
  "warning": 1.5,
  "condemned": 1.4,
  "midnight": 1.6,
  "third": 1.0,
  "hidden": 1.4,
  "secret": 1.3,
  "chain": 1.7,
  "padlock": 1.7,
  "mud": 1.0,
  "flashlight": 1.3,
  "dead battery": 1.4,
  "no signal": 1.7,
};

export const NIGHT_TERMS = new Set<string>(["DAWN", "DUSK", "MIDNIGHT", "NIGHT"]);
export const SETUP_MARKERS = ["dream", "nightmare", "warning", "warned", "promise", "remember", "later", "one day", "before it happens", "if anything happens", "third night", "never", "always", "again", "curse", "legend", "story", "told you", "locked", "secret", "strange", "odd", "wrong", "music box", "scratch", "scratches", "voice"];
export const PAYOFF_MARKERS = ["reveals", "reveal", "realize", "realizes", "truth", "was him", "was her", "all along", "now", "finally", "understand", "remember", "it was", "dead", "alive", "found", "discovered", "twist"];
